import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Travel Wishlist",
  description: "A travel to-do and wishlist app created with T3 Stack",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <TRPCReactProvider>
          {/* Global Header */}
          <header className="w-full bg-white/10 p-4 shadow-md">
            <div className="container mx-auto flex justify-between items-center">
              <h1 className="text-2xl font-bold">
                <a href="/">Travel Wishlist</a>
              </h1>
              <nav>
                <ul className="flex gap-4">
                  <li>
                    <a
                      href="/"
                      className="hover:text-[hsl(280,100%,70%)]"
                    >
                      Home
                    </a>
                  </li>
                  <li>
                    <a
                      href="/about"
                      className="hover:text-[hsl(280,100%,70%)]"
                    >
                      About
                    </a>
                  </li>
                </ul>
              </nav>
            </div>
          </header>

          {/* Main Content */}
          <main className="container mx-auto px-4 py-8">{children}</main>

          {/* Global Footer */}
          <footer className="w-full bg-white/10 p-4 mt-8">
            <div className="container mx-auto text-center">
              <p>
                The world is your oyster.
              </p>
            </div>
          </footer>
        </TRPCReactProvider>
      </body>
    </html>
  );
}



// import "~/styles/globals.css";

// import { GeistSans } from "geist/font/sans";
// import { type Metadata } from "next";

// import { TRPCReactProvider } from "~/trpc/react";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html lang="en" className={`${GeistSans.variable}`}>
//       <body>
//         <TRPCReactProvider>{children}</TRPCReactProvider>
//       </body>
//     </html>
//   );
// }
